services:
    express:
        build:
            context: ./express
        restart: always
        networks:
            - podium
        ports:
            - "3000:3000"
        volumes:
            - ./express:/usr/src/app
        env_file:
            - .env

networks:
    podium:
        driver: bridge
    vps-server_caddy:
        external: true
