services:
    express:
        build:
            context: ./express
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./express:/usr/src/app
        env_file:
            - .env