services:
  express:
    build:
      context: ./express
    restart: always
    networks:
      - podium
    ports:
      - "3000:3000"
    volumes:
      - ./express:/usr/src/app
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    networks:
      - podium
    ports:
      - "27018:27017"
    volumes:
      - ./mongo:/data/db
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - podium
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

networks:
  podium:
    driver: bridge
